CREATE TABLE IF NOT EXISTS treinos (
	id SERIAL PRIMARY KEY,
	curtidas INTEGER NOT NULL DEFAULT 0,
	"data" DATE NOT NULL DEFAULT CURRENT_DATE,
	descricao TEXT,
	foto TEXT NOT NULL,
	usuario INTEGER REFERENCES usuarios
);